# Generated by Django 5.0.1 on 2024-01-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_hotel_ids_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_ids',
            old_name='product',
            new_name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotel_ids',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hotel_ids',
            name='product_img',
        ),
        migrations.AlterField(
            model_name='hotel_ids',
            name='C_id',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='C_id',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_img',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
    ]
