# Generated by Django 5.0.1 on 2024-01-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_rename_product_hotel_ids_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_img',
        ),
        migrations.AddField(
            model_name='item',
            name='product_imgg',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel_ids',
            name='C_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='C_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.hotel_ids'),
        ),
    ]
