# Generated by Django 5.0.1 on 2024-01-26 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_rename_product_imgg_item_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='C_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='C_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.userlogin'),
        ),
    ]
