# Generated by Django 5.0.1 on 2024-04-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0006_userlogin_c_id_usersignup_c_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('Adriao Sebastiao', 'Adriao Sebastiao'), ('Afsal Kottilungal', 'Afsal Kottilungal'), ('Faseehullah Khan', 'Faseehullah Khan'), ('Kamran Khan', 'Kamran Khan'), ('AbdulRehman Tarig', 'AbdulRehman Tarig'), ('MD Maruf', 'MD Maruf'), ('Manilyn Hicken', 'Manilyn Hicken'), ('Mohammad Masud Howlader', 'Mohammad Masud Howlader'), ('Mohamed Nadeer Kundani', 'Mohamed Nadeer Kundani'), ('Mohammed Ashig', 'Mohammed Ashig'), ('Mohammed Biras', 'Mohammed Biras'), ('Mohammed Shihab', 'Mohammed Shihab'), ('Muhammadshiras Chellattanveedu', 'Muhammadshiras Chellattanveedu'), ('Muhammed Jasir', 'Muhammed Jasir'), ('Noufal thenginthodi', 'Noufal thenginthodi'), ('Reneesh Alakkandy', 'Reneesh Alakkandy'), ('Sanjul Padannakara', 'Sanjul Padannakara'), ('Shoib Hussain', 'Shoib Hussain'), ('Sonu Ravarikandi', 'Sonu Ravarikandi'), ('Sumesh Subhash', 'Sumesh Subhash'), ('Yasir Riaz', 'Yasir Riaz'), ('Satishchandra Yadav', 'Satishchandra Yadav'), ('Rajeev TR', 'Rajeev TR'), ('Mohammad Omar Faruk', 'Mohammad Omar Faruk'), ('Mohammed Ayub Ali', 'Mohammed Ayub Ali'), ('Mohamad Kamar S Bepari', 'Mohamad Kamar S Bepari')], max_length=100)),
                ('selection_type', models.CharField(choices=[('Order Submit', 'Order Submit'), ('Visit only', 'Visit only')], max_length=100)),
                ('cr_number', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('contact_person_information', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('order_forms', models.FileField(upload_to='order_forms/')),
                ('order_forms_part_2', models.FileField(upload_to='order_forms/')),
                ('block_number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='C_id',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='C_id',
        ),
        migrations.DeleteModel(
            name='hotel_ids',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
        migrations.DeleteModel(
            name='UserSignup',
        ),
    ]
