# Generated by Django 5.0.1 on 2024-04-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0007_order_remove_item_c_id_remove_usersignup_c_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='feedback_category',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Normal', 'Normal')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_person_information',
            field=models.CharField(max_length=255),
        ),
    ]
