# Generated by Django 5.0.1 on 2024-04-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0009_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='GoodCategory',
        ),
    ]
