# Generated by Django 5.0.1 on 2024-04-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0010_rename_category_goodcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodCategory',
            new_name='Category',
        ),
    ]
